### ISSUE TITLE
Missing submap key results in spurious error

### ISSUE THREAD

**Issue by johncrim** [oddbird/accoutrement#49] opened 2020-02-08 23:51 UTC
Fetching an existing key path works. Fetching a missing key path results in a weird error.

```scss
@use 'accoutrement/sass' as a;

$colors: (
  'scrollbar': (
    'thumb': #555
  )
);
@include a.add-colors($colors);

@debug a.color('scrollbar->thumb');
@debug a.color('scrollbar->background');
```

```bash
❯ sass --version
1.24.4
❯ sass submap.scss -I ./node_modules/
submap.scss:10 Debug: #555
Error: ("thumb": #555) isn't a valid CSS value.
   ╷
75 │     $new: if((type-of($new) == 'string') or (not $new), $new, '#{$new}');
   │                                                                  ^^^^
   ╵
  node_modules\accoutrement\sass\core\_strings.scss 75:66      -a-str-replace()
  node_modules\accoutrement\sass\core\_parser.scss 143:18      -a-replace()
  node_modules\accoutrement\sass\core\_parser.scss 102:14      -a-parse()
  node_modules\accoutrement\sass\core\_parser.scss 45:11       -a-get()
  node_modules\accoutrement\sass\core\_api.scss 305:9          get-token()
  node_modules\accoutrement\sass\plugin\color\_api.scss 56:11  color()
  submap.scss 11:8                                             root stylesheet
```

This is relatively severe, because I can't use `get-token` to check whether the value `'scrollbar->background'` exists - `get-token` results in the same error.

**Comment by mirisuzanne** [comment] 2020-02-10 17:54
Right, the current behavior follows the path as far as possible, and returns the last available value (in this case just `scrollbar` rather than the requested `scrollbar->background`). That was done make it possible to have non-key `#` and `->` values – but may be more problematic than it was worth.

I think #48 is already a proposed solution to this? Other solutions might be:

- missing tokens thrown an error or return `null`. These would cause breaking changes we'd have to address with deprecation and then a major release.
- make the above error/false optional-per-call? Adds overhead…

There's not much we can do about this specific error message, on it's own. It's not coming from Accoutrement, but from Sass: the result of trying to output a map as though it were a CSS value. Best we can do is make it easier to avoid the error

**Comment by johncrim** [comment] 2020-02-10 22:20
Thank you for the reply @mirisuzanne .

Certainly a solution for #48 would allow me to work around this - though I also think returning `null` would be ideal. I'd love to see `has-token` in a minor version, and returning `null` for missing keys in the next major version :)

Right now it's really hard to determine if a submap is missing, especially due to this error. Even checking for a value results in this error, and there's no `catch` in sass.

I'm confused about your statement that there's not much that can be done about this. I think the problem is using interpolation (because dart-sass requires interpolated output to be valid CSS, and a map obviously isn't). Is there another way to successfully parse the arrows and iterate the maps without calling interpolation?

I've had similar errors (`zzz isn't a valid CSS value`) when moving from node-sass to dart-sass, b/c node-sass doesn't complain when interpolated output is invalid CSS (so it works as normal text interpolation), but dart-sass throws an error (it requires that all interpolation result in valid CSS). For similar errors, I've ended up changing to string concatenation (eg `$str: '' + $var) to avoid the problems with interpolation.

I'm not nearly the SASS whiz you are, but let me know if you think that could work. Or maybe I'm missing something.

**Comment by mirisuzanne** [comment] 2020-02-11 06:14
I think you're right about the proper next steps. Happy to review a PR's, or I'll try to get to it when I can. In the meantime, I think you might be able to use `meta.type-of()` or (less reliable) `meta.inspect()` to do a check without throwing this error?

Basically, you'd want to catch any instance where the returned value still has a type of 'map' – which is (I think) the one Sass type that is not valid CSS, and throws this error, and also the most likely accidental return you'll get from the current behavior.

**Comment by johncrim** [comment] 2020-02-11 17:42
ok - I will try to create a fix and submit a PR with tests.

**Comment by jcamilleri13** [comment] 2020-06-09 17:06
Hey @johncrim, I do believe that #41 will fix this. I frequently encountered this issue on one of my projects, which is what prompted me to correct the 'silent failure' aspect in the first place. The solution I have in mind will involve a toggle to change the behaviour between returning null, throwing a warning and returning a null, or flat-out throwing an error. Would this solve your use case? I'm wrapping up the unit tests and hope to release this for review later today.

**Comment by johncrim** [comment] 2020-06-09 17:23
Thanks @jcamilleri13 - returning `null` should do the trick here, at least it makes the problem fixable/preventable using `get-token()`.

The test-case at the beginning of this issue might be a good test-case - IMO it's a simple mistake that should be easy to detect and fix, but isn't currently.

**Comment by jcamilleri13** [comment] 2020-06-10 11:48
I've run a quick test with the updated version of the library. It seems to handle your problem. Test cases, in a nutshell:

## No change in configuration ##
```
@use './node_modules/accoutrement/sass' as a;

a.$handle-missing-keys: 'null';

$colors: (
  'scrollbar': (
    'thumb': #555
  )
);
@include a.add-colors($colors);

@debug a.color('scrollbar->thumb');
@debug a.color('scrollbar->background');
```
```
> test@1.0.0 start /mnt/d/temp/test
> sass test.scss

test.scss:12 Debug: #555
Error: ("thumb": #555) isn't a valid CSS value.
   ╷
75 │     $new: if((type-of($new) == 'string') or (not $new), $new, '#{$new}');
   │                                                                  ^^^^
   ╵
  node_modules/accoutrement/sass/core/_strings.scss 75:66      -a-str-replace()
  node_modules/accoutrement/sass/core/_parser.scss 208:20      -a-replace()
  node_modules/accoutrement/sass/core/_parser.scss 102:14      -a-parse()
  node_modules/accoutrement/sass/core/_parser.scss 45:11       -a-get()
  node_modules/accoutrement/sass/core/_api.scss 305:9          get-token()
  node_modules/accoutrement/sass/plugin/color/_api.scss 56:11  color()
  test.scss 13:8                                               root stylesheet
npm ERR! code ELIFECYCLE
npm ERR! errno 65
npm ERR! test@1.0.0 start: `sass test.scss`
npm ERR! Exit status 65
```

## 'null' mode ##
```
@use './node_modules/accoutrement/sass' as a;

a.$handle-missing-keys: 'null';

$colors: (
  'scrollbar': (
    'thumb': #555
  )
);
@include a.add-colors($colors);

@debug a.color('scrollbar->thumb');
@debug a.color('scrollbar->background');
```

```
> test@1.0.0 start /mnt/d/temp/test
> sass test.scss

test.scss:12 Debug: #555
test.scss:13 Debug: null
```

## 'warn' mode ##
```
@use './node_modules/accoutrement/sass' as a;

a.$handle-missing-keys: 'warn';

$colors: (
  'scrollbar': (
    'thumb': #555
  )
);
@include a.add-colors($colors);

@debug a.color('scrollbar->thumb');
@debug a.color('scrollbar->background');
```

```
> test@1.0.0 start /mnt/d/temp/test
> sass test.scss

test.scss:12 Debug: #555
Warning: Key "scrollbar->background" not found in map
    node_modules/accoutrement/sass/core/_parser.scss 193:9       -a-replace()
    node_modules/accoutrement/sass/core/_parser.scss 102:14      -a-parse()
    node_modules/accoutrement/sass/core/_parser.scss 45:11       -a-get()
    node_modules/accoutrement/sass/core/_api.scss 305:9          get-token()
    node_modules/accoutrement/sass/plugin/color/_api.scss 56:11  color()
    test.scss 13:8                                               root stylesheet

test.scss:13 Debug: null
```

## 'error' mode ##
```
@use './node_modules/accoutrement/sass' as a;

a.$handle-missing-keys: 'error';

$colors: (
  'scrollbar': (
    'thumb': #555
  )
);
@include a.add-colors($colors);

@debug a.color('scrollbar->thumb');
@debug a.color('scrollbar->background');
```

```
> test@1.0.0 start /mnt/d/temp/test
> sass test.scss

test.scss:12 Debug: #555
Error: '[_a_replace] Key "scrollbar->background" not found in map'
    ╷
189 │         @return _a_error('Key "#{$key}" not found in map', '_a_replace');
    │                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/accoutrement/sass/core/_parser.scss 189:17      -a-replace()
  node_modules/accoutrement/sass/core/_parser.scss 102:14      -a-parse()
  node_modules/accoutrement/sass/core/_parser.scss 45:11       -a-get()
  node_modules/accoutrement/sass/core/_api.scss 305:9          get-token()
  node_modules/accoutrement/sass/plugin/color/_api.scss 56:11  color()
  test.scss 13:8                                               root stylesheet
```

**Comment by jcamilleri13** [comment] 2020-09-08 17:08
@johncrim the discussed changes have been merged, this should solve your issues in the next release.

**Closed** 2021-01-11 21:23 UTC

**Comment by johncrim** [comment] 2021-02-13 01:01
I'm still seeing this issue, in dart-sass only. I've added the following test:

```scss
  @include it('Can return submaps') {
    @include assert-equal(
      get-token($map, 'ofo'),
      (
      'zab': 4
      )
    );
  }
```

which passes when using node-sass, but fails using dart-sass:
```
$ mocha

Error: ("zab": 4) isn't a valid CSS value.
   ╷
75 │     $new: if((type-of($new) == 'string') or (not $new), $new, '#{$new}');
   │                                                                  ^^^^
   ╵
  sass\core\_strings.scss 75:66                        -a-str-replace()
  sass\core\_parser.scss 214:20                        -a-replace()
  sass\core\_parser.scss 108:14                        -a-parse()
  sass\core\_parser.scss 51:11                         -a-get()
  sass\core\_api.scss 339:9                            get-token()
  test\core\_api.scss 96:8                             @content
  node_modules\sass-true\sass\true\_tests.scss 57:5    @content
  node_modules\sass-true\sass\true\_tests.scss 28:3    test()
  node_modules\sass-true\sass\true\_tests.scss 56:3    it()
  test\core\_api.scss 94:3                             @content
  node_modules\sass-true\sass\true\_modules.scss 72:5  @content
  node_modules\sass-true\sass\true\_modules.scss 37:3  test-module()
  node_modules\sass-true\sass\true\_modules.scss 71:3  describe()
  test\core\_api.scss 40:1                             @content
  node_modules\sass-true\sass\true\_modules.scss 37:3  test-module()
```

I'm thinking it would be good to add support for running dart-sass tests alongside node-sass tests (and I've already added that locally for this repro). I'm happy to work on a fix for this...

**Comment by mirisuzanne** [comment] 2021-02-13 01:34
@johncrim That looks like a different issue, with a similar error message. In this case `("zab": 4)` is _the correct requested value_ being returned by Accoutrement, but either Dart Sass or True is refusing to compare the maps. In the original issue, the map was being returned by accident, and that's the issue we fixed.

I can look into it more, but you should get the same error even if you take Accoutrement out of the equation. I would file this on https://github.com/oddbird/true/issues/

**Comment by johncrim** [comment] 2021-02-13 04:11
Hi @mirisuzanne - thank you for the prompt reply. The issue here is that the value is never returned from accoutrement due to the error. Dart-sass is stricter than node-sass about stringizing maps, so it's failing at the specified line. It looks like the value is stringized before it gets to the `@return null` part.

I know this isn't an issue in True b/c I'm seeing the same issue in my site build with version 2.2.0 (which is why I created the test). And I'm pretty sure the dart-sass team will say this is correct behavior, that node-sass is incorrectly leniant (I recall seeing an issue about this before).

I will dig into it further and see if I can find and fix the issue. 

I also would like to add my dart-sass test config to the project, if you're interested. I think the right approach is to eventually run all the same tests on dart-sass and node-sass (except tests using `@use` would be dart-sass only). But to get started, I would skip big swaths of tests that don't pass, eg the return values are different between dart-sass and node-sass (eg dart-sass includes units in cases where node-sass doesn't). So I'm volunteering to at least get it started.

**Comment by mirisuzanne** [comment] 2021-02-13 18:01
@johncrim I see what your saying about the error coming from Accoutrement. But I'm still confused about how you got to this error, based on the ofo/zab test case you posted. I can't reproduce it with that code in Dart Sass. The failing line is inside our internal `str-replace` function - which is not called by the test. 

I can still see the error with your original code, until I add the configuration required for this fix:

```scss
@use '../node_modules/accoutrement/sass' with ($handle-missing-keys: 'null');
```

> I also would like to add my dart-sass test config to the project, if you're interested. I think the right approach is to eventually run all the same tests on dart-sass and node-sass (except tests using @use would be dart-sass only).

Since Node Sass has officially been deprecated, I think we can probably release a new version that drops support for it entirely. But I'm open to seeing what you have in mind.

**Comment by johncrim** [comment] 2021-02-13 18:41
@mirisuzanne - I'm seeing the same, i.e. this error occurs in dart-sass only, and only when `$handle-missing-keys` is `silent`. When `$handle-missing-keys` is set to one of the new values, it no longer happens; and it also doesn't happen regardless of the `$handle-missing-keys` value on node-sass.

My statement above "It looks like the value is stringized before it gets to the `@return null` part" is incorrect and misleading. But I still think it should be fixed, and a test case included for dart-sass to prevent future regression.

**Comment by jcamilleri13** [comment] 2021-02-14 00:04
Hi @johncrim @mirisuzanne 

Sorry for being so late to the party. I do believe I have encountered this error at some point myself:

> Error: ("zab": 4) isn't a valid CSS value.
>    ╷
> 75 │     $new: if((type-of($new) == 'string') or (not $new), $new, '#{$new}');
>    │                                                                  ^^^^
>    ╵

When I bumped into it, the issue was with the interpolation of the $new value, i.e. `#{$new}`. Replacing it with `inspect($new)` had corrected it I believe - there was a similar issue we had solved in the same manner, #36 I believe. I may be parking up the wrong tree, but have you tried that just in case that's what's causing the error?

**Comment by johncrim** [comment] 2021-02-14 21:42
Thank you @jcamilleri13  - that's very helpful. Yes, it's a similar issue, eg dart-sass will error instead of interpolating a map.

I suppose the question is: What is the correct behavior? If a map should be interpolated into the string, then `inspect` is the right fix. If it should not be interpolated, and the reference left in the string instead, then I think I have a good fix. In the PR, I modified this test (which passes on node-sass):

```scss
  $map: (
    'this': 0,
    'this->that': 1,
    'foo': (
      'baz': 2,
      'three': (
        'abc': '#foo->baz',
        'def': '#this'
      ),
    ),
    'ofo': (
      'zab': 4
    ),
    'dop': '#ofo->nope',
    'dip': '#that->baz',
  );

  @include it('Fails elegantly when keys are not found') {
    @include assert-equal(
      (get-token($map, 'dop'), get-token($map, 'dip')),
      ('("zab": 4)->nope', '#that->baz')
    );
  }
```

to:

``` scss
  @include it('Fails elegantly when keys are not found') {
    @include assert-equal(
      (get-token($map, 'dop'), get-token($map, 'dip')),
      ('#ofo->nope', '#that->baz')
    );
  }
```

Because I consider it better (more consistent) behavior. I don't think that interpolating a map is correct in -a-str-replace, b/c it's never going to work out correctly eg for subsequent replacement and never going to be expected (that's probably also true for interpolating lists). 

If you prefer `inspect()` instead, that means the previous test output (`'("zab": 4)->nope'`) is preferable.

Any thoughts on the PR?
https://github.com/oddbird/accoutrement/pull/60/files

**Comment by jcamilleri13** [comment] 2021-02-14 22:15
Hey @johncrim,

I'm also of the opinion that the map interpolation behaviour is a bit weird. but @mirisuzanne had made the call to leave it as is so we don't break backwards compatibility, which is also an understandable position. That was why we had decided to put the alternate behaviours behind a configuration switch. I have no issue with updating the behaviour personally, but perhaps it would be best to tie it in to any other breaking changes that need to be made to the library, so we break everything at once so to speak?

**Comment by mirisuzanne** [comment] 2021-02-15 23:57
@johncrim Your solution absolutely makes the most sense here. Sorry I was struggling to follow along with your concerns. 

- We can't really rely on `inspect()` for user-facing output, because it is explicitly intended for debugging, with no promise about the format it returns. The other place we use it is just to create the memo lookup table internally, which feels safer. 
- This is the better default behavior anyway

But like @jcamilleri13 mentioned, it would be a potentially breaking change, so we need to handle it with some caution. But the only other breaking-change I have in mind is moving to Sass Modules and dropping support for Node-Sass (I expect big performance wins from the new nested map functions). 

And that's not a quick update, so… Maybe we just do a major release with this fix?

**Comment by johncrim** [comment] 2021-02-17 03:26
@mirisuzanne and @jcamilleri13 - here's a case that fails with the new `$handle-missing-keys` setting when using `get-token()` to get a submap - I thought I'd seen this, but then had some difficulty reproducing it, so then I concluded it was old age forgetfulness. Anyhow, while trying to get precise in the changelog I was able to come up with a concise repro:

```scss
// file: submap-null-setting.scss
@use './node_modules/accoutrement/sass' as a with (
  $handle-missing-keys: 'null'
);

$map: (
  'ofo': (
    'zab': 4
  ),
  'foo': (
    'three': '#ofo'
  )
);

$zab: a.get-token($map, 'ofo->zab');
@debug $zab;

$ofo: a.get-token($map, 'ofo');
@debug $ofo;

$ofo: a.get-token($map, 'foo->three');
@debug $ofo;
```

then: 

```
❯ sass submap-null-setting.scss
submap-null-setting.scss:16 Debug: 4
submap-null-setting.scss:19 Debug: ("zab": 4)
Error: ("zab": 4) isn't a valid CSS value.
   ╷
64 │   $string: if((type-of($string) == 'string'), $string, '#{$string}');
   │                                                           ^^^^^^^
   ╵
  node_modules\accoutrement\sass\core\_strings.scss 64:59  -a-str-replace()
  node_modules\accoutrement\sass\core\_parser.scss 225:14  -a-replace()
  node_modules\accoutrement\sass\core\_parser.scss 108:14  -a-parse()
  node_modules\accoutrement\sass\core\_parser.scss 51:11   -a-get()
  node_modules\accoutrement\sass\core\_api.scss 339:9      get-token()
  node_modules\accoutrement\sass\core\_parser.scss 182:13  -a-replace()
  node_modules\accoutrement\sass\core\_parser.scss 108:14  -a-parse()
  node_modules\accoutrement\sass\core\_parser.scss 51:11   -a-get()
  node_modules\accoutrement\sass\core\_api.scss 339:9      get-token()
  submap-null-setting.scss 21:7                            root stylesheet
```

I have a unit test for this already, I'm next testing whether my recent fix handles this or whether it's a new bug.

**Comment by johncrim** [comment] 2021-02-17 05:02
The bug has a nearly identical cause, but is behaviorally different, so I opened a new issue: #61

**Comment by mirisuzanne** [comment] 2021-02-23 00:39
Released: https://github.com/oddbird/accoutrement/releases/tag/v3.0.0

Thanks again!
